webapp/akun/urls.py
from django.urls import path
from .import  views

urlpatterns=[
     path('regist_siswa/',views.regist_siswa.as_view(), name='regist_siswa'),
     path('regist_guru/',views.regist_guru.as_view(), name='regist_guru'),
     path('edit_kuis/<int:pk>/',views.edit_kuis.as_view(), name='edit_kuis'),
     path('edit_siswa/<int:pk>/',views.edit_siswa.as_view(), name='edit_siswa'),
     path('login_siswa/',views.login_siswa, name='login_siswa'),
     path('login_guru/',views.login_guru, name='login_guru'),
     path('guru_profile/<int:pk>/',views.guru_profile, name='guru_profile'),
     path('siswa_profile/<int:pk>/',views.siswa_profile, name='siswa_profile'),
     path('edit_profile/<int:pk>/', views.edit_guru_profile.as_view(), name='edit_guru_profile'),
     path('logout/',views.logout_view, name='logout'),
     path('home_siswa',views.home_siswa,name='home_siswa'),
     path('profile_siswa',views.profile_siswa,name='profile_siswa'),
     path('hapus_siswa/<int:pk>/',views.hapus_siswa,name='hapus_siswa'),
     path('hapus_hasil_belajar/<int:pk>/', views.hapus_hasil_belajar, name='hapus_hasil_belajar'),
     path('home_guru',views.home_guru,name='home_guru'),
     path('data_siswa', views.data_siswa, name='data_siswa'),
     path('data_kuis', views.data_kuis, name='data_kuis'),
     path('data_hasil_belajar', views.data_hasil_belajar, name='data_hasil_belajar'),
      path('export-to-pdf/', views.export_to_pdf, name='export_to_pdf'),
    
]   

webapp/materi/urls.py
from django.urls import path
from .import  views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
     path('beranda_1/',views.beranda_1, name='beranda_1'),
      path('siswa/kuis_bab1', views.kuis_bab1, name='kuis_bab1'),
       path('semua_kuis', views.semua_kuis, name='semua_kuis'),
    path('kuis<int:quiz_id>', views.kuis_view, name='kuis'), 
     path('soal_evaluasi<int:quiz_id>', views.soal_evaluasi, name='soal_evaluasi'), 
     path('hasil_kuis/<int:quiz_id>/', views.hasil_kuis, name='hasil_kuis'),
    path("program",views.program,name="program"), 
     path("bahasa_pemrograman",views.bahasa_pemrograman,name="bahasa_pemrograman"), 
     path("interpreter_compiler",views.interpreter_compiler,name="interpreter_compiler"), 
     path("bahasa_python",views.bahasa_python,name="bahasa_python"),
     path("program_sederhana",views.program_sederhana,name="program_sederhana"),
     path("kuis_bab1",views.kuis_bab1,name="kuis_bab1"),
     path("beranda2",views.beranda2,name="beranda2"), 
     path("tipe_data",views.tipe_data,name="tipe_data"), 
     path("variabel",views.variabel,name="variabel"), 
     path("operator",views.operator,name="operator"), 
     path("kuis_bab2",views.kuis_bab2,name="kuis_bab2"), 
     path("beranda3",views.beranda3,name="beranda3"), 
     path("percabangan",views.percabangan,name="percabangan"), 
     path("percabangan_if",views.percabangan_if,name="percabangan_if"), 
     path("percabangan_if_else",views.percabangan_if_else,name="percabangan_if_else"), 
     path("percabangan_elif",views.percabangan_elif,name="percabangan_elif"), 
     path("percabangan_bersarang",views.percabangan_bersarang,name="percabangan_bersarang"), 
     path("kuis_bab3",views.kuis_bab3,name="kuis_bab3"), 
     path("beranda4",views.beranda4,name="beranda4"), 
     path("perulangan",views.perulangan,name="perulangan"), 
     path("perulangan_while",views.perulangan_while,name="perulangan_while"), 
     path("perulangan_for",views.perulangan_for,name="perulangan_for"), 
     path("kuis_bab4",views.kuis_bab4,name="kuis_bab4"), 
     path("beranda5",views.beranda5,name="beranda5"),
     path("fungsi",views.fungsi,name="fungsi"),
     path("membuat_fungsi",views.membuat_fungsi,name="membuat_fungsi"),
     path("cara_kerja_fungsi",views.cara_kerja_fungsi,name="cara_kerja_fungsi"),
     path("parameterisasi_fungsi",views.parameterisasi_fungsi,name="parameterisasi_fungsi"),
     path("variabel_lokal_global",views.variabel_lokal_global,name="variabel_lokal_global"),
     path("parameter_formal_aktual",views.parameter_formal_aktual,name="parameter_formal_aktual"),
     path("parameter_wajib_opsional",views.parameter_wajib_opsional,name="parameter_wajib_opsional"),
     path("sintak_dasar",views.sintak_dasar,name="sintak_dasar"),
     path("komentar",views.komentar,name="komentar"),
     path("operator_perbandingan",views.operator_perbandingan,name="operator_perbandingan"),
     path("operator_penugasan",views.operator_penugasan,name="operator_penugasan"),
     path("operator_logika",views.operator_logika,name="operator_logika"),
     path("input",views.input,name="input"),
     path("output",views.output,name="output"),
     path("beranda3",views.beranda3,name="beranda3"),
     path("kuis_bab5",views.kuis_bab5,name="kuis_bab5"),
     path("beranda6",views.beranda6,name="beranda6"),
     path("kuis_bab6",views.kuis_bab6,name="kuis_bab6"),
     path("beranda7",views.beranda7,name="beranda7"),
     path("kuis_bab7",views.kuis_bab7,name="kuis_bab7"),
     path("evaluasi",views.evaluasi,name="evaluasi"),
     path("ending",views.ending,name="ending"),
         
]   

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('base.urls')),
    path('akun/', include('akun.urls')),
    path('materi/', include('materi.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/materi/models.py
from django.db import models
from akun.models import User
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    kkm = models.IntegerField(default = 3)
  
    class Meta:
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text1 = models.TextField(default = " ",blank=True, null=True)
    text2 = models.TextField( default=" ",blank=True, null=True)
    quiz_img = models.ImageField(upload_to='quiz_images', default=' ', blank=True, null=True, verbose_name='Quiz image')
    bobot_nilai = models.IntegerField(default=20, blank=True, null=True)  # Field bobot nilai boleh kosong dan boleh null dengan default 20
  
    def __str__(self):
        return f"{self.text1[:50]},{self.quiz_img}, {self.text2[:50]}"
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.question.text1[:50]},{self.question.text2[:50]}, {self.text[:20]}"

class QuizSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}, {self.quiz.title}"

class UserRank(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rank = models.IntegerField(null=True, blank=True)
    total_score = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.rank}, {self.user.username}"

@receiver(post_save, sender=QuizSubmission)
def update_leaderboard(sender, instance, created, **kwargs):
    if created:
        update_leaderboard()



def update_leaderboard():
    # Count the sum of scores for all users
    user_scores = (QuizSubmission.objects.values('user').annotate(total_score=Sum('score')).order_by('-total_score'))

    # Update rank based on the sorted list
    rank = 1
    for entry in user_scores:
        user_id = entry['user']
        total_score = entry['total_score']

        user_rank, created = UserRank.objects.get_or_create(user_id=user_id)
        user_rank.rank = rank
        user_rank.total_score = total_score
        user_rank.save()

        rank += 1

webapp/materi/forms.py
from django import forms
from .models import Quiz
from akun.models import Siswa

class KuisForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['title', 'description', 'kkm'] 

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'kkm': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class QuizSubmissionFilterForm(forms.Form):
    quiz = forms.ModelChoiceField(queryset=Quiz.objects.all(), required=False, label='Kuis')
    kelas_siswa = forms.ChoiceField(choices=Siswa.OPSI_KELAS, required=False, label='Kelas Siswa')

webapp/templates/materi/kuis copy.html
{% extends 'index.html' %}

{% block title %}{{quiz.title}}{% endblock title %}

{% block content %}

    <h1 class="display-4 text-center my-5">{{quiz.title}} - ({{quiz.question_set.all|length}} soal)</h1>

    <div class="container">
        <div class="d-flex justify-content-between">
          
           <p> Waktu Pengerjaan : </p><span class="fs-5" id="timer">-</span>
        </div>

        <div class="questions my-4">
            {% for question in quiz.question_set.all %}
            <div class="card mb-2 question">
                <div class="card-header fw-bold">
                    Soal {{forloop.counter}}
                </div>
                <div class="card-body">
                    <p class="card-text">{{question.text1}}</p>

                    {% if question.quiz_img %}
                    <img src="{{ question.quiz_img.url }}" alt="Quiz Image" class="img-fluid mb-3" id="quizImg{{forloop.counter}}"
                     style="width: 100%; max-width: 500px; height: auto;">
                    <script>
                        // JavaScript code to hide image if it's not available
                        var quizImg = document.getElementById("quizImg{{forloop.counter}}");
                        if (!quizImg.complete || quizImg.naturalHeight === 0) {
                            quizImg.style.display = "none";
                        }
                        else{
                            quizImg.style.display = "block";
                        }
                    </script>
                {% endif %}

                    <p class="card-text">{{question.text2}}</p>
                    {% for option in question.choice_set.all %}
                    <div class="form-check">
                        <label class="form-check-label" for="{{option.id}}">
                            <input class="form-check-input" value="{{option.text}}" type="radio" name="{{option.question.id}}" id="{{option.id}}">
                            {{option.text}}
                        </label>
                        {% if option.is_correct %}
                        <span class="visually-hidden correct-answer">{{option.text}}</span>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        <form action="" method="post" id="quiz-form">
            {% csrf_token %}
            <!-- hidden input field for score -->
            <input type="hidden" name="score" value="0" id="user-score">

            <!-- submit button -->
            <button type="submit" class="btn btn-primary" id="submit-button">Kirim Jawaban</button>
        </form>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    <script>
        // Element HTML
        var submitButton = document.getElementById("submit-button");
        var timerSpan = document.getElementById("timer");
        var quizForm = document.getElementById("quiz-form");
        var questions = document.querySelectorAll(".question");
        var userScoreInput = document.getElementById("user-score");
    
        // Periksa apakah halaman baru saja dimuat
        var halamanDimuat = sessionStorage.getItem('halamanDimuat');
    
        // Jika halaman baru saja dimuat, perbarui halaman setelah 3 detik
        if (!halamanDimuat) {
            setTimeout(function () {
                location.reload();
            }, 3000);
            sessionStorage.setItem('halamanDimuat', true);
        }
    
        // Periksa apakah ada nilai timer yang disimpan di sessionStorage
        var waktuTersimpan = sessionStorage.getItem('quizTimer');
        var durasiKuis = waktuTersimpan ? parseInt(waktuTersimpan) : (questions.length) * 180; // konversi dalam detik
    
        // Fungsi untuk memperbarui Timer
        function perbaruiTimer() {
            var menit = Math.floor(durasiKuis / 60);
            var detik = durasiKuis % 60;
    
            timerSpan.innerText = menit + "m" + detik + 's';
    
            // Periksa apakah waktu sudah habis
            if (durasiKuis <= 0) {
                // Secara otomatis kirim kuis
                clearTimeout(idTimerKuis);
                kirimKuis();
            } else if (document.getElementById("message-div")) {
                clearTimeout(idTimerKuis);
                sorotJawabanBenar();
            } else {
                // Kurangi nilai timer sebesar 1 detik
                durasiKuis--;
                // Simpan nilai timer yang diperbarui di sessionStorage
                sessionStorage.setItem('quizTimer', durasiKuis.toString());
            }
        }
    
        // Fungsi untuk mengirimkan kuis
        function kirimKuis() {
            // Hitung nilai
            hitungNilai();
    
            // Hapus nilai timer yang tersimpan dari sessionStorage
            sessionStorage.removeItem('quizTimer');
    
            // Kirim kuis
            quizForm.submit();
        }
    
        // Periksa jawaban yang benar dan hitung nilai
        function hitungNilai() {
            var nilai = 0;
    
            // Loop melalui setiap pertanyaan
            questions.forEach(pertanyaan => {
                var inputTerpilih = pertanyaan.querySelector('input:checked');
                var jawabanBenar = pertanyaan.querySelector(".correct-answer").innerText;
    
                // Periksa apakah jawaban benar atau tidak
                if (inputTerpilih && inputTerpilih.value === jawabanBenar) {
                    nilai += 20;
                }
            });
    
            // Perbarui nilai yang tersembunyi dengan nilai di formulir
            userScoreInput.value = nilai;
        }
    
        // Sorot jawaban yang benar saat menampilkan hasil
        function sorotJawabanBenar() {
            questions.forEach(pertanyaan => {
                var jawabanBenar = pertanyaan.querySelector(".correct-answer");
            });
    
            // Nonaktifkan tombol submit
            submitButton.disabled = true;
    
            // Nonaktifkan semua opsi
            var opsi = document.querySelectorAll(".form-check-input");
            opsi.forEach(pilihan => {
                pilihan.disabled = true;
            });
        }
    
        // Tambahkan Event Listener ke tombol Submit
        submitButton.addEventListener("click", kirimKuis);
    
        // Interval Timer
        idTimerKuis = setInterval(perbaruiTimer, 1000);
    
    </script>
    

{% endblock content %}

webapp/templates/materi/soal_evaluasi.html
{% extends 'index.html' %}

{% block title %}{{quiz.title}}{% endblock title %}

{% block content %}

    <h5 class="display-4 text-center my-5">{{quiz.title}} - ({{quiz.question_set.all|length}} soal)</h5>

    <div class="container">
        <div class="d-flex justify-content-between">
          
           <p> Waktu Pengerjaan : </p><span class="fs-5" id="timer">-</span>
        </div>

        <div class="questions my-4">
            {% for question in quiz.question_set.all %}
            <div class="card mb-2 question">
                <div class="card-header fw-bold" style="background-color:#0C2D57; color:white;">
                    Soal {{forloop.counter}}
                </div>
                <div class="card-body" style="background-color:#C9D7DD;">
                    <p class="card-text">{{question.text1}}</p>

                    {% if question.quiz_img %}
                    <img src="{{ question.quiz_img.url }}" alt="Quiz Image" class="img-fluid mb-3" id="quizImg{{forloop.counter}}"
                     style="width: 100%; max-width: 500px; height: auto;">
                    <script>
                        // JavaScript code to hide image if it's not available
                        var quizImg = document.getElementById("quizImg{{forloop.counter}}");
                        if (!quizImg.complete || quizImg.naturalHeight === 0) {
                            quizImg.style.display = "none";
                        }
                        else{
                            quizImg.style.display = "block";
                        }
                    </script>
                {% endif %}

                    <p class="card-text">{{question.text2}}</p>
                    {% for option in question.choice_set.all %}
                    <div class="form-check">
                        <label class="form-check-label" for="{{option.id}}">
                            <input class="form-check-input" value="{{option.text}}" type="radio" name="{{option.question.id}}" id="{{option.id}}">
                            {{option.text}}
                        </label>
                        {% if option.is_correct %}
                        <span class="visually-hidden correct-answer">{{option.text}}</span>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        <form action="" method="post" id="quiz-form">
            {% csrf_token %}
            <!-- hidden input field for score -->
            <input type="hidden" name="score" value="0" id="user-score">

            <!-- submit button -->
            <button type="submit" class="btn btn-primary" id="submit-button">Kirim Jawaban</button>
        </form>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    <script>
        // Element HTML
        var submitButton = document.getElementById("submit-button");
        var timerSpan = document.getElementById("timer");
        var quizForm = document.getElementById("quiz-form");
        var questions = document.querySelectorAll(".question");
        var userScoreInput = document.getElementById("user-score");
    
    
        // Periksa apakah ada nilai timer yang disimpan di sessionStorage
        var waktuTersimpan = sessionStorage.getItem('quizTimer');
        var durasiKuis = waktuTersimpan ? parseInt(waktuTersimpan) : (questions.length) * 180; // konversi dalam detik
    
        // Fungsi untuk memperbarui Timer
        function perbaruiTimer() {
            var menit = Math.floor(durasiKuis / 60);
            var detik = durasiKuis % 60;
    
            timerSpan.innerText = menit + "m" + detik + 's';
    
            // Periksa apakah waktu sudah habis
            if (durasiKuis <= 0) {
                // Secara otomatis kirim kuis
                clearTimeout(idTimerKuis);
                kirimKuis();
            } else if (document.getElementById("message-div")) {
                clearTimeout(idTimerKuis);
                sorotJawabanBenar();
            } else {
                // Kurangi nilai timer sebesar 1 detik
                durasiKuis--;
                // Simpan nilai timer yang diperbarui di sessionStorage
                sessionStorage.setItem('quizTimer', durasiKuis.toString());
            }
        }
    
        // Fungsi untuk mengirimkan kuis
        function kirimKuis() {
            // Hitung nilai
            hitungNilai();
    
            // Hapus nilai timer yang tersimpan dari sessionStorage
            sessionStorage.removeItem('quizTimer');
    
            // Kirim kuis
            quizForm.submit();
        }
    
        // Periksa jawaban yang benar dan hitung nilai
        function hitungNilai() {
            var nilai = 0;
    
            // Loop melalui setiap pertanyaan
            questions.forEach(pertanyaan => {
                var inputTerpilih = pertanyaan.querySelector('input:checked');
                var jawabanBenar = pertanyaan.querySelector(".correct-answer").innerText;
    
                // Periksa apakah jawaban benar atau tidak
                if (inputTerpilih && inputTerpilih.value === jawabanBenar) {
                    nilai += 5;
                }
            });
    
            // Perbarui nilai yang tersembunyi dengan nilai di formulir
            userScoreInput.value = nilai;
        }
    
        // Sorot jawaban yang benar saat menampilkan hasil
        function sorotJawabanBenar() {
            questions.forEach(pertanyaan => {
                var jawabanBenar = pertanyaan.querySelector(".correct-answer");
            });
    
            // Nonaktifkan tombol submit
            submitButton.disabled = true;
    
            // Nonaktifkan semua opsi
            var opsi = document.querySelectorAll(".form-check-input");
            opsi.forEach(pilihan => {
                pilihan.disabled = true;
            });
        }
    
        // Tambahkan Event Listener ke tombol Submit
        submitButton.addEventListener("click", kirimKuis);
    
        // Interval Timer
        idTimerKuis = setInterval(perbaruiTimer, 1000);
    
    // Simpan jawaban yang dipilih ke sessionStorage saat pengguna memilih
document.querySelectorAll('.form-check-input').forEach(function(input) {
    input.addEventListener('change', function() {
        sessionStorage.setItem(input.name, input.value);
    });
});

// Periksa apakah ada jawaban yang dipilih di sessionStorage saat halaman dimuat kembali
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.form-check-input').forEach(function(input) {
        var savedValue = sessionStorage.getItem(input.name);
        if (savedValue && savedValue === input.value) {
            input.checked = true;
        }
    });
});

// Saat pengguna menekan tombol submit, hapus jawaban yang disimpan dari sessionStorage
var submitButton = document.getElementById('submit-button');
if (submitButton) {
    submitButton.addEventListener('click', function() {
        document.querySelectorAll('.form-check-input').forEach(function(input) {
            sessionStorage.removeItem(input.name);
        });
    });
}
    
    </script>
    

{% endblock content %}